movies = 
[
    {
        "crew": "Frank Darabont (dir.), Tim Robbins, Morgan Freeman",
        "fullTitle": "The Shawshank Redemption (1994)",
        "id": "tt0111161",
        "imDbRating": 9.2,
        "imDbRatingCount": 2620728,
        "image": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 1,
        "title": "The Shawshank Redemption",
        "year": 1994
    },
    {
        "crew": "Francis Ford Coppola (dir.), Marlon Brando, Al Pacino",
        "fullTitle": "The Godfather (1972)",
        "id": "tt0068646",
        "imDbRating": 9.2,
        "imDbRatingCount": 1814966,
        "image": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 2,
        "title": "The Godfather",
        "year": 1972
    },
    {
        "crew": "Christopher Nolan (dir.), Christian Bale, Heath Ledger",
        "fullTitle": "The Dark Knight (2008)",
        "id": "tt0468569",
        "imDbRating": 9,
        "imDbRatingCount": 2592559,
        "image": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 3,
        "title": "The Dark Knight",
        "year": 2008
    },
    {
        "crew": "Francis Ford Coppola (dir.), Al Pacino, Robert De Niro",
        "fullTitle": "The Godfather Part II (1974)",
        "id": "tt0071562",
        "imDbRating": 9,
        "imDbRatingCount": 1246747,
        "image": "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 4,
        "title": "The Godfather Part II",
        "year": 1974
    },
    {
        "crew": "Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb",
        "fullTitle": "12 Angry Men (1957)",
        "id": "tt0050083",
        "imDbRating": 8.9,
        "imDbRatingCount": 774247,
        "image": "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 5,
        "title": "12 Angry Men",
        "year": 1957
    },
    {
        "crew": "Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes",
        "fullTitle": "Schindler's List (1993)",
        "id": "tt0108052",
        "imDbRating": 8.9,
        "imDbRatingCount": 1331027,
        "image": "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 6,
        "title": "Schindler's List",
        "year": 1993
    },
    {
        "crew": "Peter Jackson (dir.), Elijah Wood, Viggo Mortensen",
        "fullTitle": "The Lord of the Rings: The Return of the King (2003)",
        "id": "tt0167260",
        "imDbRating": 8.9,
        "imDbRatingCount": 1798067,
        "image": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 7,
        "title": "The Lord of the Rings: The Return of the King",
        "year": 2003
    },
    {
        "crew": "Quentin Tarantino (dir.), John Travolta, Uma Thurman",
        "fullTitle": "Pulp Fiction (1994)",
        "id": "tt0110912",
        "imDbRating": 8.9,
        "imDbRatingCount": 2006954,
        "image": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 8,
        "title": "Pulp Fiction",
        "year": 1994
    },
    {
        "crew": "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
        "fullTitle": "The Lord of the Rings: The Fellowship of the Ring (2001)",
        "id": "tt0120737",
        "imDbRating": 8.8,
        "imDbRatingCount": 1819380,
        "image": "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 9,
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "year": 2001
    },
    {
        "crew": "Sergio Leone (dir.), Clint Eastwood, Eli Wallach",
        "fullTitle": "The Good, the Bad and the Ugly (1966)",
        "id": "tt0060196",
        "imDbRating": 8.8,
        "imDbRatingCount": 749982,
        "image": "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 10,
        "title": "The Good, the Bad and the Ugly",
        "year": 1966
    },
    {
        "crew": "Robert Zemeckis (dir.), Tom Hanks, Robin Wright",
        "fullTitle": "Forrest Gump (1994)",
        "id": "tt0109830",
        "imDbRating": 8.8,
        "imDbRatingCount": 2026393,
        "image": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 11,
        "title": "Forrest Gump",
        "year": 1994
    },
    {
        "crew": "David Fincher (dir.), Brad Pitt, Edward Norton",
        "fullTitle": "Fight Club (1999)",
        "id": "tt0137523",
        "imDbRating": 8.7,
        "imDbRatingCount": 2065838,
        "image": "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 12,
        "title": "Fight Club",
        "year": 1999
    },
    {
        "crew": "Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt",
        "fullTitle": "Inception (2010)",
        "id": "tt1375666",
        "imDbRating": 8.7,
        "imDbRatingCount": 2299343,
        "image": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 13,
        "title": "Inception",
        "year": 2010
    },
    {
        "crew": "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
        "fullTitle": "The Lord of the Rings: The Two Towers (2002)",
        "id": "tt0167261",
        "imDbRating": 8.7,
        "imDbRatingCount": 1623753,
        "image": "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 14,
        "title": "The Lord of the Rings: The Two Towers",
        "year": 2002
    },
    {
        "crew": "Irvin Kershner (dir.), Mark Hamill, Harrison Ford",
        "fullTitle": "Star Wars: Episode V - The Empire Strikes Back (1980)",
        "id": "tt0080684",
        "imDbRating": 8.7,
        "imDbRatingCount": 1268373,
        "image": "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 15,
        "title": "Star Wars: Episode V - The Empire Strikes Back",
        "year": 1980
    },
    {
        "crew": "Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne",
        "fullTitle": "The Matrix (1999)",
        "id": "tt0133093",
        "imDbRating": 8.7,
        "imDbRatingCount": 1878206,
        "image": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 16,
        "title": "The Matrix",
        "year": 1999
    },
    {
        "crew": "Martin Scorsese (dir.), Robert De Niro, Ray Liotta",
        "fullTitle": "Goodfellas (1990)",
        "id": "tt0099685",
        "imDbRating": 8.7,
        "imDbRatingCount": 1135023,
        "image": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 17,
        "title": "Goodfellas",
        "year": 1990
    },
    {
        "crew": "Milos Forman (dir.), Jack Nicholson, Louise Fletcher",
        "fullTitle": "One Flew Over the Cuckoo's Nest (1975)",
        "id": "tt0073486",
        "imDbRating": 8.6,
        "imDbRatingCount": 992621,
        "image": "https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 18,
        "title": "One Flew Over the Cuckoo's Nest",
        "year": 1975
    },
    {
        "crew": "David Fincher (dir.), Morgan Freeman, Brad Pitt",
        "fullTitle": "Se7en (1995)",
        "id": "tt0114369",
        "imDbRating": 8.6,
        "imDbRatingCount": 1610615,
        "image": "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 19,
        "title": "Se7en",
        "year": 1995
    },
    {
        "crew": "Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura",
        "fullTitle": "Seven Samurai (1954)",
        "id": "tt0047478",
        "imDbRating": 8.6,
        "imDbRatingCount": 342054,
        "image": "https://m.media-amazon.com/images/M/MV5BNWQ3OTM4ZGItMWEwZi00MjI5LWI3YzgtNTYwNWRkNmIzMGI5XkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 20,
        "title": "Seven Samurai",
        "year": 1954
    },
    {
        "crew": "Frank Capra (dir.), James Stewart, Donna Reed",
        "fullTitle": "It's a Wonderful Life (1946)",
        "id": "tt0038650",
        "imDbRating": 8.6,
        "imDbRatingCount": 449262,
        "image": "https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 21,
        "title": "It's a Wonderful Life",
        "year": 1946
    },
    {
        "crew": "Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins",
        "fullTitle": "The Silence of the Lambs (1991)",
        "id": "tt0102926",
        "imDbRating": 8.6,
        "imDbRatingCount": 1401685,
        "image": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 22,
        "title": "The Silence of the Lambs",
        "year": 1991
    },
    {
        "crew": "Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino",
        "fullTitle": "City of God (2002)",
        "id": "tt0317248",
        "imDbRating": 8.6,
        "imDbRatingCount": 747172,
        "image": "https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 23,
        "title": "City of God",
        "year": 2002
    },
    {
        "crew": "Steven Spielberg (dir.), Tom Hanks, Matt Damon",
        "fullTitle": "Saving Private Ryan (1998)",
        "id": "tt0120815",
        "imDbRating": 8.6,
        "imDbRatingCount": 1363694,
        "image": "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 24,
        "title": "Saving Private Ryan",
        "year": 1998
    },
    {
        "crew": "Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi",
        "fullTitle": "Life Is Beautiful (1997)",
        "id": "tt0118799",
        "imDbRating": 8.6,
        "imDbRatingCount": 683361,
        "image": "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 25,
        "title": "Life Is Beautiful",
        "year": 1997
    },
    {
        "crew": "Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan",
        "fullTitle": "The Green Mile (1999)",
        "id": "tt0120689",
        "imDbRating": 8.6,
        "imDbRatingCount": 1273473,
        "image": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 26,
        "title": "The Green Mile",
        "year": 1999
    },
    {
        "crew": "Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway",
        "fullTitle": "Interstellar (2014)",
        "id": "tt0816692",
        "imDbRating": 8.6,
        "imDbRatingCount": 1762949,
        "image": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 27,
        "title": "Interstellar",
        "year": 2014
    },
    {
        "crew": "George Lucas (dir.), Mark Hamill, Harrison Ford",
        "fullTitle": "Star Wars (1977)",
        "id": "tt0076759",
        "imDbRating": 8.6,
        "imDbRatingCount": 1341022,
        "image": "https://m.media-amazon.com/images/M/MV5BNzg4MjQxNTQtZmI5My00YjMwLWJlMjUtMmJlY2U2ZWFlNzY1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 28,
        "title": "Star Wars",
        "year": 1977
    },
    {
        "crew": "James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton",
        "fullTitle": "Terminator 2: Judgment Day (1991)",
        "id": "tt0103064",
        "imDbRating": 8.5,
        "imDbRatingCount": 1079532,
        "image": "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 29,
        "title": "Terminator 2: Judgment Day",
        "year": 1991
    },
    {
        "crew": "Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd",
        "fullTitle": "Back to the Future (1985)",
        "id": "tt0088763",
        "imDbRating": 8.5,
        "imDbRatingCount": 1176997,
        "image": "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 30,
        "title": "Back to the Future",
        "year": 1985
    },
    {
        "crew": "Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette",
        "fullTitle": "Spirited Away (2001)",
        "id": "tt0245429",
        "imDbRating": 8.5,
        "imDbRatingCount": 743926,
        "image": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 31,
        "title": "Spirited Away",
        "year": 2001
    },
    {
        "crew": "Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh",
        "fullTitle": "Psycho (1960)",
        "id": "tt0054215",
        "imDbRating": 8.5,
        "imDbRatingCount": 660344,
        "image": "https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 32,
        "title": "Psycho",
        "year": 1960
    },
    {
        "crew": "Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann",
        "fullTitle": "The Pianist (2002)",
        "id": "tt0253474",
        "imDbRating": 8.5,
        "imDbRatingCount": 815011,
        "image": "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 33,
        "title": "The Pianist",
        "year": 2002
    },
    {
        "crew": "Luc Besson (dir.), Jean Reno, Gary Oldman",
        "fullTitle": "Léon: The Professional (1994)",
        "id": "tt0110413",
        "imDbRating": 8.5,
        "imDbRatingCount": 1139404,
        "image": "https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 34,
        "title": "Léon: The Professional",
        "year": 1994
    },
    {
        "crew": "Bong Joon Ho (dir.), Song Kang-ho, Sun-kyun Lee",
        "fullTitle": "Parasite (2019)",
        "id": "tt6751668",
        "imDbRating": 8.5,
        "imDbRatingCount": 764284,
        "image": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 35,
        "title": "Parasite",
        "year": 2019
    },
    {
        "crew": "Roger Allers (dir.), Matthew Broderick, Jeremy Irons",
        "fullTitle": "The Lion King (1994)",
        "id": "tt0110357",
        "imDbRating": 8.5,
        "imDbRatingCount": 1037724,
        "image": "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 36,
        "title": "The Lion King",
        "year": 1994
    },
    {
        "crew": "Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix",
        "fullTitle": "Gladiator (2000)",
        "id": "tt0172495",
        "imDbRating": 8.5,
        "imDbRatingCount": 1470769,
        "image": "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 37,
        "title": "Gladiator",
        "year": 2000
    },
    {
        "crew": "Tony Kaye (dir.), Edward Norton, Edward Furlong",
        "fullTitle": "American History X (1998)",
        "id": "tt0120586",
        "imDbRating": 8.5,
        "imDbRatingCount": 1106042,
        "image": "https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 38,
        "title": "American History X",
        "year": 1998
    },
    {
        "crew": "Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon",
        "fullTitle": "The Departed (2006)",
        "id": "tt0407887",
        "imDbRating": 8.5,
        "imDbRatingCount": 1301202,
        "image": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 39,
        "title": "The Departed",
        "year": 2006
    },
    {
        "crew": "Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne",
        "fullTitle": "The Usual Suspects (1995)",
        "id": "tt0114814",
        "imDbRating": 8.5,
        "imDbRatingCount": 1069781,
        "image": "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 40,
        "title": "The Usual Suspects",
        "year": 1995
    },
    {
        "crew": "Christopher Nolan (dir.), Christian Bale, Hugh Jackman",
        "fullTitle": "The Prestige (2006)",
        "id": "tt0482571",
        "imDbRating": 8.5,
        "imDbRatingCount": 1308083,
        "image": "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 41,
        "title": "The Prestige",
        "year": 2006
    },
    {
        "crew": "Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman",
        "fullTitle": "Casablanca (1942)",
        "id": "tt0034583",
        "imDbRating": 8.5,
        "imDbRatingCount": 564560,
        "image": "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 42,
        "title": "Casablanca",
        "year": 1942
    },
    {
        "crew": "Damien Chazelle (dir.), Miles Teller, J.K. Simmons",
        "fullTitle": "Whiplash (2014)",
        "id": "tt2582802",
        "imDbRating": 8.5,
        "imDbRatingCount": 827725,
        "image": "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 43,
        "title": "Whiplash",
        "year": 2014
    },
    {
        "crew": "Olivier Nakache (dir.), François Cluzet, Omar Sy",
        "fullTitle": "The Intouchables (2011)",
        "id": "tt1675434",
        "imDbRating": 8.5,
        "imDbRatingCount": 841216,
        "image": "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 44,
        "title": "The Intouchables",
        "year": 2011
    },
    {
        "crew": "Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama",
        "fullTitle": "Harakiri (1962)",
        "id": "tt0056058",
        "imDbRating": 8.5,
        "imDbRatingCount": 55381,
        "image": "https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 45,
        "title": "Harakiri",
        "year": 1962
    },
    {
        "crew": "Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi",
        "fullTitle": "Grave of the Fireflies (1988)",
        "id": "tt0095327",
        "imDbRating": 8.4,
        "imDbRatingCount": 271248,
        "image": "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 46,
        "title": "Grave of the Fireflies",
        "year": 1988
    },
    {
        "crew": "Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard",
        "fullTitle": "Modern Times (1936)",
        "id": "tt0027977",
        "imDbRating": 8.4,
        "imDbRatingCount": 239582,
        "image": "https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 47,
        "title": "Modern Times",
        "year": 1936
    },
    {
        "crew": "Sergio Leone (dir.), Henry Fonda, Charles Bronson",
        "fullTitle": "Once Upon a Time in the West (1968)",
        "id": "tt0064116",
        "imDbRating": 8.4,
        "imDbRatingCount": 325913,
        "image": "https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 48,
        "title": "Once Upon a Time in the West",
        "year": 1968
    },
    {
        "crew": "Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly",
        "fullTitle": "Top Gun: Maverick (2022)",
        "id": "tt1745960",
        "imDbRating": 8.4,
        "imDbRatingCount": 258514,
        "image": "https://m.media-amazon.com/images/M/MV5BOWQwOTA1ZDQtNzk3Yi00ZmVmLWFiZGYtNjdjNThiYjJhNzRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 49,
        "title": "Top Gun: Maverick",
        "year": 2022
    },
    {
        "crew": "Alfred Hitchcock (dir.), James Stewart, Grace Kelly",
        "fullTitle": "Rear Window (1954)",
        "id": "tt0047396",
        "imDbRating": 8.4,
        "imDbRatingCount": 485097,
        "image": "https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 50,
        "title": "Rear Window",
        "year": 1954
    },
    {
        "crew": "Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt",
        "fullTitle": "Alien (1979)",
        "id": "tt0078748",
        "imDbRating": 8.4,
        "imDbRatingCount": 864141,
        "image": "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 51,
        "title": "Alien",
        "year": 1979
    },
    {
        "crew": "Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill",
        "fullTitle": "City Lights (1931)",
        "id": "tt0021749",
        "imDbRating": 8.4,
        "imDbRatingCount": 183050,
        "image": "https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 52,
        "title": "City Lights",
        "year": 1931
    },
    {
        "crew": "Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale",
        "fullTitle": "Cinema Paradiso (1988)",
        "id": "tt0095765",
        "imDbRating": 8.4,
        "imDbRatingCount": 257377,
        "image": "https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 53,
        "title": "Cinema Paradiso",
        "year": 1988
    },
    {
        "crew": "Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss",
        "fullTitle": "Memento (2000)",
        "id": "tt0209144",
        "imDbRating": 8.4,
        "imDbRatingCount": 1218384,
        "image": "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 54,
        "title": "Memento",
        "year": 2000
    },
    {
        "crew": "Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando",
        "fullTitle": "Apocalypse Now (1979)",
        "id": "tt0078788",
        "imDbRating": 8.4,
        "imDbRatingCount": 657776,
        "image": "https://m.media-amazon.com/images/M/MV5BYmQyNTA1ZGItNjZjMi00NzFlLWEzMWEtNWMwN2Q2MjJhYzEyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 55,
        "title": "Apocalypse Now",
        "year": 1979
    },
    {
        "crew": "Steven Spielberg (dir.), Harrison Ford, Karen Allen",
        "fullTitle": "Indiana Jones and the Raiders of the Lost Ark (1981)",
        "id": "tt0082971",
        "imDbRating": 8.4,
        "imDbRatingCount": 952303,
        "image": "https://m.media-amazon.com/images/M/MV5BNTU2ODkyY2MtMjU1NC00NjE1LWEzYjgtMWQ3MzRhMTE0NDc0XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 56,
        "title": "Indiana Jones and the Raiders of the Lost Ark",
        "year": 1981
    },
    {
        "crew": "Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz",
        "fullTitle": "Django Unchained (2012)",
        "id": "tt1853728",
        "imDbRating": 8.4,
        "imDbRatingCount": 1516305,
        "image": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 57,
        "title": "Django Unchained",
        "year": 2012
    },
    {
        "crew": "Andrew Stanton (dir.), Ben Burtt, Elissa Knight",
        "fullTitle": "WALL·E (2008)",
        "id": "tt0910970",
        "imDbRating": 8.4,
        "imDbRatingCount": 1096754,
        "image": "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 58,
        "title": "WALL·E",
        "year": 2008
    },
    {
        "crew": "Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck",
        "fullTitle": "The Lives of Others (2006)",
        "id": "tt0405094",
        "imDbRating": 8.4,
        "imDbRatingCount": 385993,
        "image": "https://m.media-amazon.com/images/M/MV5BNmQyNmJjM2ItNTQzYi00ZjMxLWFjMDYtZjUyN2YwZDk5YWQ2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 59,
        "title": "The Lives of Others",
        "year": 2006
    },
    {
        "crew": "Billy Wilder (dir.), William Holden, Gloria Swanson",
        "fullTitle": "Sunset Blvd. (1950)",
        "id": "tt0043014",
        "imDbRating": 8.4,
        "imDbRatingCount": 219585,
        "image": "https://m.media-amazon.com/images/M/MV5BMTU0NTkyNzYwMF5BMl5BanBnXkFtZTgwMDU0NDk5MTI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 60,
        "title": "Sunset Blvd.",
        "year": 1950
    },
    {
        "crew": "Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker",
        "fullTitle": "Paths of Glory (1957)",
        "id": "tt0050825",
        "imDbRating": 8.4,
        "imDbRatingCount": 195255,
        "image": "https://m.media-amazon.com/images/M/MV5BOTI5Nzc0OTMtYzBkMS00NjkxLThmM2UtNjM2ODgxN2M5NjNkXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 61,
        "title": "Paths of Glory",
        "year": 1957
    },
    {
        "crew": "Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall",
        "fullTitle": "The Shining (1980)",
        "id": "tt0081505",
        "imDbRating": 8.4,
        "imDbRatingCount": 998209,
        "image": "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 62,
        "title": "The Shining",
        "year": 1980
    },
    {
        "crew": "Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard",
        "fullTitle": "The Great Dictator (1940)",
        "id": "tt0032553",
        "imDbRating": 8.4,
        "imDbRatingCount": 221926,
        "image": "https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 63,
        "title": "The Great Dictator",
        "year": 1940
    },
    {
        "crew": "Billy Wilder (dir.), Tyrone Power, Marlene Dietrich",
        "fullTitle": "Witness for the Prosecution (1957)",
        "id": "tt0051201",
        "imDbRating": 8.4,
        "imDbRatingCount": 123628,
        "image": "https://m.media-amazon.com/images/M/MV5BNDQwODU5OWYtNDcyNi00MDQ1LThiOGMtZDkwNWJiM2Y3MDg0XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 64,
        "title": "Witness for the Prosecution",
        "year": 1957
    },
    {
        "crew": "Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth",
        "fullTitle": "Avengers: Infinity War (2018)",
        "id": "tt4154756",
        "imDbRating": 8.4,
        "imDbRatingCount": 1041566,
        "image": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 65,
        "title": "Avengers: Infinity War",
        "year": 2018
    },
    {
        "crew": "James Cameron (dir.), Sigourney Weaver, Michael Biehn",
        "fullTitle": "Aliens (1986)",
        "id": "tt0090605",
        "imDbRating": 8.3,
        "imDbRatingCount": 706395,
        "image": "https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 66,
        "title": "Aliens",
        "year": 1986
    },
    {
        "crew": "Sam Mendes (dir.), Kevin Spacey, Annette Bening",
        "fullTitle": "American Beauty (1999)",
        "id": "tt0169547",
        "imDbRating": 8.3,
        "imDbRatingCount": 1139934,
        "image": "https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 67,
        "title": "American Beauty",
        "year": 1999
    },
    {
        "crew": "Stanley Kubrick (dir.), Peter Sellers, George C. Scott",
        "fullTitle": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)",
        "id": "tt0057012",
        "imDbRating": 8.3,
        "imDbRatingCount": 484897,
        "image": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 68,
        "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
        "year": 1964
    },
    {
        "crew": "Bob Persichetti (dir.), Shameik Moore, Jake Johnson",
        "fullTitle": "Spider-Man: Into the Spider-Verse (2018)",
        "id": "tt4633694",
        "imDbRating": 8.3,
        "imDbRatingCount": 506103,
        "image": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 69,
        "title": "Spider-Man: Into the Spider-Verse",
        "year": 2018
    },
    {
        "crew": "Christopher Nolan (dir.), Christian Bale, Tom Hardy",
        "fullTitle": "The Dark Knight Rises (2012)",
        "id": "tt1345836",
        "imDbRating": 8.3,
        "imDbRatingCount": 1672442,
        "image": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 70,
        "title": "The Dark Knight Rises",
        "year": 2012
    },
    {
        "crew": "Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae",
        "fullTitle": "Oldboy (2003)",
        "id": "tt0364569",
        "imDbRating": 8.3,
        "imDbRatingCount": 568444,
        "image": "https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 71,
        "title": "Oldboy",
        "year": 2003
    },
    {
        "crew": "Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro",
        "fullTitle": "Joker (2019)",
        "id": "tt7286456",
        "imDbRating": 8.3,
        "imDbRatingCount": 1223378,
        "image": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 72,
        "title": "Joker",
        "year": 2019
    },
    {
        "crew": "Milos Forman (dir.), F. Murray Abraham, Tom Hulce",
        "fullTitle": "Amadeus (1984)",
        "id": "tt0086879",
        "imDbRating": 8.3,
        "imDbRatingCount": 396830,
        "image": "https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 73,
        "title": "Amadeus",
        "year": 1984
    },
    {
        "crew": "Mel Gibson (dir.), Mel Gibson, Sophie Marceau",
        "fullTitle": "Braveheart (1995)",
        "id": "tt0112573",
        "imDbRating": 8.3,
        "imDbRatingCount": 1025033,
        "image": "https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 74,
        "title": "Braveheart",
        "year": 1995
    },
    {
        "crew": "John Lasseter (dir.), Tom Hanks, Tim Allen",
        "fullTitle": "Toy Story (1995)",
        "id": "tt0114709",
        "imDbRating": 8.3,
        "imDbRatingCount": 976745,
        "image": "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 75,
        "title": "Toy Story",
        "year": 1995
    },
    {
        "crew": "Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal",
        "fullTitle": "Coco (2017)",
        "id": "tt2380307",
        "imDbRating": 8.3,
        "imDbRatingCount": 489007,
        "image": "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 76,
        "title": "Coco",
        "year": 2017
    },
    {
        "crew": "Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer",
        "fullTitle": "The Boat (1981)",
        "id": "tt0082096",
        "imDbRating": 8.3,
        "imDbRatingCount": 248850,
        "image": "https://m.media-amazon.com/images/M/MV5BNDBjMWUxNTUtNjZiNi00YzJhLTgzNzUtMTRiY2FkZmMzYTNjXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 77,
        "title": "The Boat",
        "year": 1981
    },
    {
        "crew": "Quentin Tarantino (dir.), Brad Pitt, Diane Kruger",
        "fullTitle": "Inglourious Basterds (2009)",
        "id": "tt0361748",
        "imDbRating": 8.3,
        "imDbRatingCount": 1413906,
        "image": "https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 78,
        "title": "Inglourious Basterds",
        "year": 2009
    },
    {
        "crew": "Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida",
        "fullTitle": "Princess Mononoke (1997)",
        "id": "tt0119698",
        "imDbRating": 8.3,
        "imDbRatingCount": 387445,
        "image": "https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 79,
        "title": "Princess Mononoke",
        "year": 1997
    },
    {
        "crew": "Anthony Russo (dir.), Robert Downey Jr., Chris Evans",
        "fullTitle": "Avengers: Endgame (2019)",
        "id": "tt4154796",
        "imDbRating": 8.3,
        "imDbRatingCount": 1084318,
        "image": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 80,
        "title": "Avengers: Endgame",
        "year": 2019
    },
    {
        "crew": "Sergio Leone (dir.), Robert De Niro, James Woods",
        "fullTitle": "Once Upon a Time in America (1984)",
        "id": "tt0087843",
        "imDbRating": 8.3,
        "imDbRatingCount": 347046,
        "image": "https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 81,
        "title": "Once Upon a Time in America",
        "year": 1984
    },
    {
        "crew": "Gus Van Sant (dir.), Robin Williams, Matt Damon",
        "fullTitle": "Good Will Hunting (1997)",
        "id": "tt0119217",
        "imDbRating": 8.3,
        "imDbRatingCount": 948841,
        "image": "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 82,
        "title": "Good Will Hunting",
        "year": 1997
    },
    {
        "crew": "Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi",
        "fullTitle": "Your Name. (2016)",
        "id": "tt5311514",
        "imDbRating": 8.3,
        "imDbRatingCount": 257960,
        "image": "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 83,
        "title": "Your Name.",
        "year": 2016
    },
    {
        "crew": "Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto",
        "fullTitle": "Requiem for a Dream (2000)",
        "id": "tt0180093",
        "imDbRating": 8.3,
        "imDbRatingCount": 829242,
        "image": "https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 84,
        "title": "Requiem for a Dream",
        "year": 2000
    },
    {
        "crew": "Lee Unkrich (dir.), Tom Hanks, Tim Allen",
        "fullTitle": "Toy Story 3 (2010)",
        "id": "tt0435761",
        "imDbRating": 8.3,
        "imDbRatingCount": 823735,
        "image": "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 85,
        "title": "Toy Story 3",
        "year": 2010
    },
    {
        "crew": "Stanley Donen (dir.), Gene Kelly, Donald O'Connor",
        "fullTitle": "Singin' in the Rain (1952)",
        "id": "tt0045152",
        "imDbRating": 8.3,
        "imDbRatingCount": 239704,
        "image": "https://m.media-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 86,
        "title": "Singin' in the Rain",
        "year": 1952
    },
    {
        "crew": "Rajkumar Hirani (dir.), Aamir Khan, Madhavan",
        "fullTitle": "3 Idiots (2009)",
        "id": "tt1187043",
        "imDbRating": 8.3,
        "imDbRatingCount": 391696,
        "image": "https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 87,
        "title": "3 Idiots",
        "year": 2009
    },
    {
        "crew": "Richard Marquand (dir.), Mark Hamill, Harrison Ford",
        "fullTitle": "Star Wars: Episode VI - Return of the Jedi (1983)",
        "id": "tt0086190",
        "imDbRating": 8.3,
        "imDbRatingCount": 1035932,
        "image": "https://m.media-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 88,
        "title": "Star Wars: Episode VI - Return of the Jedi",
        "year": 1983
    },
    {
        "crew": "Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada",
        "fullTitle": "High and Low (1963)",
        "id": "tt0057565",
        "imDbRating": 8.3,
        "imDbRatingCount": 43937,
        "image": "https://m.media-amazon.com/images/M/MV5BOTI4NTNhZDMtMWNkZi00MTRmLWJmZDQtMmJkMGVmZTEzODlhXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 89,
        "title": "High and Low",
        "year": 1963
    },
    {
        "crew": "Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood",
        "fullTitle": "2001: A Space Odyssey (1968)",
        "id": "tt0062622",
        "imDbRating": 8.3,
        "imDbRatingCount": 658446,
        "image": "https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 90,
        "title": "2001: A Space Odyssey",
        "year": 1968
    },
    {
        "crew": "Michel Gondry (dir.), Jim Carrey, Kate Winslet",
        "fullTitle": "Eternal Sunshine of the Spotless Mind (2004)",
        "id": "tt0338013",
        "imDbRating": 8.3,
        "imDbRatingCount": 991019,
        "image": "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 91,
        "title": "Eternal Sunshine of the Spotless Mind",
        "year": 2004
    },
    {
        "crew": "Quentin Tarantino (dir.), Harvey Keitel, Tim Roth",
        "fullTitle": "Reservoir Dogs (1992)",
        "id": "tt0105236",
        "imDbRating": 8.3,
        "imDbRatingCount": 1000718,
        "image": "https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 92,
        "title": "Reservoir Dogs",
        "year": 1992
    },
    {
        "crew": "Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw",
        "fullTitle": "Capernaum (2018)",
        "id": "tt8267604",
        "imDbRating": 8.3,
        "imDbRatingCount": 86928,
        "image": "https://m.media-amazon.com/images/M/MV5BY2Y3OWNkMTctYzNjYS00NWVkLTg4OWEtY2YxN2I3NDhlYzE0XkEyXkFqcGdeQXVyMTI3ODAyMzE2._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 93,
        "title": "Capernaum",
        "year": 2018
    },
    {
        "crew": "Orson Welles (dir.), Orson Welles, Joseph Cotten",
        "fullTitle": "Citizen Kane (1941)",
        "id": "tt0033467",
        "imDbRating": 8.3,
        "imDbRatingCount": 437721,
        "image": "https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 94,
        "title": "Citizen Kane",
        "year": 1941
    },
    {
        "crew": "David Lean (dir.), Peter O'Toole, Alec Guinness",
        "fullTitle": "Lawrence of Arabia (1962)",
        "id": "tt0056172",
        "imDbRating": 8.3,
        "imDbRatingCount": 290656,
        "image": "https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 95,
        "title": "Lawrence of Arabia",
        "year": 1962
    },
    {
        "crew": "Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen",
        "fullTitle": "The Hunt (2012)",
        "id": "tt2106476",
        "imDbRating": 8.3,
        "imDbRatingCount": 323827,
        "image": "https://m.media-amazon.com/images/M/MV5BMTg2NDg3ODg4NF5BMl5BanBnXkFtZTcwNzk3NTc3Nw@@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 96,
        "title": "The Hunt",
        "year": 2012
    },
    {
        "crew": "Fritz Lang (dir.), Peter Lorre, Ellen Widmann",
        "fullTitle": "M (1931)",
        "id": "tt0022100",
        "imDbRating": 8.3,
        "imDbRatingCount": 156580,
        "image": "https://m.media-amazon.com/images/M/MV5BODA4ODk3OTEzMF5BMl5BanBnXkFtZTgwMTQ2ODMwMzE@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 97,
        "title": "M",
        "year": 1931
    },
    {
        "crew": "Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint",
        "fullTitle": "North by Northwest (1959)",
        "id": "tt0053125",
        "imDbRating": 8.3,
        "imDbRatingCount": 324412,
        "image": "https://m.media-amazon.com/images/M/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 98,
        "title": "North by Northwest",
        "year": 1959
    },
    {
        "crew": "Alfred Hitchcock (dir.), James Stewart, Kim Novak",
        "fullTitle": "Vertigo (1958)",
        "id": "tt0052357",
        "imDbRating": 8.2,
        "imDbRatingCount": 397755,
        "image": "https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 99,
        "title": "Vertigo",
        "year": 1958
    },
    {
        "crew": "Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova",
        "fullTitle": "Come and See (1985)",
        "id": "tt0091251",
        "imDbRating": 8.2,
        "imDbRatingCount": 77035,
        "image": "https://m.media-amazon.com/images/M/MV5BODM4Njg0NTAtYjI5Ny00ZjAxLTkwNmItZTMxMWU5M2U3M2RjXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX256_CR0,12,256_AL_.jpg",
        "rank": 100,
        "title": "Come and See",
        "year": 1985
    }
]
